name: to_do_list
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  http: '>=0.11.3+12'
  redux: "^3.0.0"
  flutter_redux: "^0.5.1"
  shared_preferences: "^0.4.2"
  flutter_redux_dev_tools: "^0.3.0"
  redux_dev_tools: "^0.4.0"
  equatable: '^0.4.0'


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true